services:
  - type: web
    name: video-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        value: ep-bold-snow-ahobrvb8-pooler.c-3.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: MedVerify
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: STORAGE_ENDPOINT
        value: https://s3.us-east-1.wasabisys.com
      - key: STORAGE_REGION
        value: us-east-1
      - key: STORAGE_ACCESS_KEY
        sync: false
      - key: STORAGE_SECRET_KEY
        sync: false
      - key: STORAGE_BUCKET
        sync: false
      - key: RESEND_API_KEY
        generateValue: true
      - key: EMAIL_FROM
        generateValue: true
      - key: FRONTEND_URL
        value: http://localhost:5173
    healthCheckPath: /
